version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
  build:
    commands:
      - echo "Build stage - Copying files"
      - aws s3 sync frontend s3://frontend-bucket-s3 --delete
artifacts:
  base-directory: 'frontend' 
  files:
    - '**/*' # This includes all files in the frontend directory
