version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  pre_build:
    commands:
      - echo Installing source dependencies...
  build:
    commands:
      - echo Build started on `date`
      - cd lambda
      - zip -r ../functions.zip . # Zips everything in the current directory
      - cd ..
      - aws cloudformation package --template-file lambda-template.yml --s3-bucket cf-artifact-bucket --output-template-file output-lambda-template.yml
artifacts:
  files:
    - functions.zip
    - lambda-template.yml
    - output-lambda-template.yml
