AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS CloudFormation template for creating two Lambda functions.

Resources:
  IndexPhotosFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index-photos.lambda_handler
      Runtime: python3.12
      Code:
        S3Bucket: ''
        S3Key: ''   
      Description: A Lambda function for indexing photos.
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt LambdaExecutionRole.Arn

  SearchPhotosFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: search-photos.lambda_handler
      Runtime: python3.12
      Code:
        S3Bucket: '' 
        S3Key: ''
      Description: A Lambda function for searching photos.
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt LambdaExecutionRole.Arn

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
              # Include any additional permissions your Lambda functions need here

Outputs:
  IndexPhotosFunctionName:
    Description: "The name of the Index Photos Lambda function."
    Value: !Ref IndexPhotosFunction

  IndexPhotosFunctionArn:
    Description: "The ARN of the Index Photos Lambda function."
    Value: !GetAtt IndexPhotosFunction.Arn

  SearchPhotosFunctionName:
    Description: "The name of the Search Photos Lambda function."
    Value: !Ref SearchPhotosFunction

  SearchPhotosFunctionArn:
    Description: "The ARN of the Search Photos Lambda function."
    Value: !GetAtt SearchPhotosFunction.Arn
