version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.12
  build:
    commands:
      - aws cloudformation package --template-file lambda-template.yml --s3-bucket codepipeline-us-east-2-441521765130 --output-template-file output-lambda-template.yml
 files:
    - lambda-template.yml
    - output-lambda-template.yml
